name: Wayback Download

on:
  workflow_dispatch: 

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install downloader
        run: gem install wayback_machine_downloader

      - name: Download site
        run: wayback_machine_downloader https://web.archive.org/web/20240215144406/https://aniwatch.to/

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-archive
          path: websites/
